import type { ModelProviderPreset } from "@openbot/domain";

/** Reviewed API routes, not an assertion that an account can run every suggested model. */
export const modelProviderPresets: ModelProviderPreset[] = [
  {
    id: "openai",
    name: "OpenAI",
    protocol: "openai-chat",
    endpoints: [{ name: "Global", baseUrl: "https://api.openai.com/v1" }],
    suggestedModels: ["gpt-5.6-terra", "gpt-5.6-sol", "gpt-5.6-luna"],
    discovery: true,
    description: "GPT models through the standard OpenAI API.",
    docsUrl: "https://developers.openai.com/api/docs/models",
  },
  {
    id: "anthropic",
    name: "Anthropic / Claude",
    protocol: "anthropic-messages",
    endpoints: [{ name: "Global", baseUrl: "https://api.anthropic.com" }],
    suggestedModels: ["claude-sonnet-5", "claude-opus-5", "claude-haiku-4-5-20251001"],
    discovery: true,
    description: "Claude models through the native Messages API.",
    docsUrl: "https://platform.claude.com/docs/en/models/overview",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    protocol: "openai-chat",
    endpoints: [
      { name: "Global", baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai" },
    ],
    suggestedModels: ["gemini-3.8-flash", "gemini-3.5-flash-lite"],
    discovery: true,
    description: "Gemini text chat through Google's beta OpenAI compatibility API.",
    docsUrl: "https://ai.google.dev/gemini-api/docs/openai",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    protocol: "openai-chat",
    endpoints: [{ name: "Standard API", baseUrl: "https://api.deepseek.com" }],
    suggestedModels: ["deepseek-v4-flash", "deepseek-v4-pro"],
    discovery: true,
    description: "DeepSeek models through its standard API.",
    docsUrl: "https://api-docs.deepseek.com/",
  },
  {
    id: "kimi",
    name: "Kimi / Moonshot",
    protocol: "openai-chat",
    endpoints: [
      { name: "China", baseUrl: "https://api.moonshot.cn/v1" },
      { name: "Global", baseUrl: "https://api.moonshot.ai/v1" },
    ],
    suggestedModels: ["kimi-k2.6", "kimi-k3", "kimi-k2.7-code"],
    discovery: true,
    description: "Choose the region that issued your Moonshot API key.",
    docsUrl: "https://platform.kimi.ai/docs/models",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    protocol: "openai-chat",
    endpoints: [{ name: "Global", baseUrl: "https://openrouter.ai/api/v1" }],
    suggestedModels: [],
    discovery: true,
    description: "Discover text model IDs, or enter a specific model from the provider catalog.",
    docsUrl: "https://openrouter.ai/docs/quickstart",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow / 硅基流动",
    protocol: "openai-chat",
    endpoints: [
      { name: "China", baseUrl: "https://api.siliconflow.cn/v1" },
      { name: "Global", baseUrl: "https://api.siliconflow.com/v1" },
    ],
    suggestedModels: [],
    discovery: true,
    description: "Discover text chat models using the region that issued your API key.",
    docsUrl: "https://docs.siliconflow.cn/docs/userguide/quickstart",
  },
  {
    id: "dashscope",
    name: "Alibaba Cloud Model Studio / 阿里云百炼",
    protocol: "openai-chat",
    endpoints: [
      { name: "China", baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1" },
      { name: "International", baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1" },
      { name: "US", baseUrl: "https://dashscope-us.aliyuncs.com/compatible-mode/v1" },
    ],
    suggestedModels: ["qwen3.8-max"],
    discovery: false,
    description: "Select your API key's region and enter a model enabled in that workspace.",
    docsUrl: "https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
  },
  {
    id: "zai",
    name: "Zhipu / Z.AI / 智谱",
    protocol: "openai-chat",
    endpoints: [
      { name: "China", baseUrl: "https://open.bigmodel.cn/api/paas/v4" },
      { name: "Global", baseUrl: "https://api.z.ai/api/paas/v4" },
    ],
    suggestedModels: ["glm-5.3", "glm-4.7-flash"],
    discovery: false,
    description: "Standard GLM API access; model IDs and API keys depend on the region.",
    docsUrl: "https://docs.z.ai/api-reference/llm/chat-completion",
  },
  {
    id: "minimax",
    name: "MiniMax",
    protocol: "openai-chat",
    endpoints: [
      { name: "China", baseUrl: "https://api.minimax.cn/v1" },
      { name: "Global", baseUrl: "https://api.minimax.io/v1" },
    ],
    suggestedModels: ["MiniMax-M3", "MiniMax-M2.7"],
    discovery: true,
    description: "MiniMax text chat with reasoning kept separate from the visible answer.",
    docsUrl: "https://platform.minimax.io/docs/api-reference/text-openai-api",
  },
  {
    id: "ark",
    name: "Volcengine Ark / 火山方舟",
    protocol: "openai-chat",
    endpoints: [{ name: "Beijing", baseUrl: "https://ark.cn-beijing.volces.com/api/v3" }],
    suggestedModels: [],
    discovery: false,
    description: "Enter the inference endpoint or model ID enabled in your Ark account.",
    docsUrl: "https://www.volcengine.com/docs/82379/1330310",
  },
  {
    id: "custom",
    name: "Custom OpenAI-compatible API / 自定义兼容 API",
    protocol: "openai-chat",
    endpoints: [],
    suggestedModels: [],
    discovery: true,
    description: "Use an exact HTTPS endpoint authorized by the Server operator.",
    docsUrl: "https://developers.openai.com/api/reference/resources/chat/subresources/completions",
  },
];
